version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: credit_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - credit-network

  # API网关
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - user-management-service
      - student-info-service
      - teacher-info-service
      - affair-management-service
      - general-application-service
    networks:
      - credit-network

  # 用户管理服务
  user-management-service:
    build: ./user-management-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - PORT=8081
    networks:
      - credit-network

  # 学生信息服务
  student-info-service:
    build: ./student-info-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    environment:
      - PORT=8084
    networks:
      - credit-network

  # 教师信息服务
  teacher-info-service:
    build: ./teacher-info-service
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      - PORT=8085
    networks:
      - credit-network

  # 事项管理服务
  affair-management-service:
    build: ./affair-management-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      - PORT=8083
    networks:
      - credit-network

  # 通用申请服务
  general-application-service:
    build: ./general-application-service
    ports:
      - "8086:8086"
    depends_on:
      - postgres
    environment:
      - PORT=8086
    networks:
      - credit-network

  # 前端应用
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    networks:
      - credit-network

volumes:
  postgres_data:


networks:
  credit-network:
    driver: bridge
