services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15
    container_name: credit_management_postgres
    environment:
      POSTGRES_DB: credit_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - credit_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d credit_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API网关
  api-gateway:
    build: ./api-gateway
    container_name: credit_management_gateway
    ports:
      - "8080:8080"
    environment:
      - CREDIT_ACTIVITY_SERVICE_URL=http://credit-activity-service:8083
      - AUTH_SERVICE_URL=http://auth-service:8081
      - USER_SERVICE_URL=http://user-service:8084
      - STUDENT_SERVICE_URL=http://student-service:8085
      - TEACHER_SERVICE_URL=http://teacher-service:8086
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - credit_network

  # 认证服务
  auth-service:
    build: ./auth-service
    container_name: credit_management_auth
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=credit_management
      - JWT_SECRET=your-secret-key
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - credit_network

  # 学分活动服务（合并了事务和申请管理功能）
  credit-activity-service:
    build: ./credit-activity-service
    container_name: credit_management_credit_activity
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=credit_management
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - credit_network

  # 用户管理服务
  user-service:
    build: ./user-management-service
    container_name: credit_management_user
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=credit_management
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - credit_network

  # 学生信息服务
  student-service:
    build: ./student-info-service
    container_name: credit_management_student
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=credit_management
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - credit_network

  # 教师信息服务
  teacher-service:
    build: ./teacher-info-service
    container_name: credit_management_teacher
    ports:
      - "8086:8086"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=credit_management
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - credit_network

  # 前端应用
  frontend:
    build: ./frontend
    container_name: credit_management_frontend
    ports:
      - "3000:80"
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - credit_network

volumes:
  postgres_data:
  affair_uploads:

networks:
  credit_network:
    driver: bridge
