apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "credit_management"
  JWT_SECRET: "your-secret-key"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: credit-management/api-gateway:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
  labels:
    app: user-management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      containers:
        - name: user-management-service
          image: credit-management/user-management-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  selector:
    app: user-management-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: credit-management/auth-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-management-service
  labels:
    app: application-management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application-management-service
  template:
    metadata:
      labels:
        app: application-management-service
    spec:
      containers:
        - name: application-management-service
          image: credit-management/application-management-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: uploads-volume
              mountPath: /root/uploads
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: application-management-service
spec:
  selector:
    app: application-management-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affair-management-service
  labels:
    app: affair-management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: affair-management-service
  template:
    metadata:
      labels:
        app: affair-management-service
    spec:
      containers:
        - name: affair-management-service
          image: credit-management/affair-management-service:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: affair-management-service
spec:
  selector:
    app: affair-management-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-info-service
  labels:
    app: student-info-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-info-service
  template:
    metadata:
      labels:
        app: student-info-service
    spec:
      containers:
        - name: student-info-service
          image: credit-management/student-info-service:latest
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: student-info-service
spec:
  selector:
    app: student-info-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-info-service
  labels:
    app: teacher-info-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teacher-info-service
  template:
    metadata:
      labels:
        app: teacher-info-service
    spec:
      containers:
        - name: teacher-info-service
          image: credit-management/teacher-info-service:latest
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: teacher-info-service
spec:
  selector:
    app: teacher-info-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: credit-management/frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
